service: golend-todo

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

dotenv:
  path: ./.env
  basePath: ./
  include:

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  region: ap-southeast-2

functions:
  todoFindAll:
    handler: src/functions/todo.function.findAll
    memorySize: 1024
    events:
      - http:
          path: api/todo
          method: get
          cors: true
  todoFindById:
    handler: src/functions/todo.function.findById
    memorySize: 1024
    events:
      - http:
          path: api/todo/{id}
          method: get
          cors: true
  todoCreate:
    handler: src/functions/todo.function.create
    memorySize: 1024
    events:
      - http:
          path: api/todo
          method: post
          cors: true
  todoUpdate:
    handler: src/functions/todo.function.update
    memorySize: 1024
    events:
      - http:
          path: api/todo/{id}
          method: put
          cors: true
  todoDelete:
    handler: src/functions/todo.function.delete
    memorySize: 1024
    events:
      - http:
          path: api/todo/{id}
          method: delete
          cors: true
