service: golend-todo

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

dotenv:
  path: ./.env
  basePath: ./
  include:

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  region: ap-southeast-2

functions:
